## what is this? https://github.com/realm/SwiftLint
# how to install? https://github.com/realm/SwiftLint
# where to put? <path_to_workspace>/<project_name>/.swiftlint.yml (at the same level as <project_name>.xcodeproj)

opt_in_rules:
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - overridden_super_call
  - private_outlet
  - switch_case_on_newline
  - redundant_nil_coalescing
 
disabled_rules: # rule identifiers to exclude from running
  - force_cast

included: # paths to include during linting. `--path` is ignored if present.
  - CodingTest
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods 

function_body_length:
  warning: 60
file_length:
  warning: 600
  error: 700
line_length:
  warning: 160
  error: 180
type_name:
  max_length:
    warning: 45
    error: 50
type_body_length:
  warning: 300
  error: 400
